name: Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - SonarQube
      - dependency-check
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [build, depchecktest]  # Asegúrate de que estos nombres coinciden exactamente con los nombres de los jobs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
