name: Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - SonarQube
      - Dependency Check
    types:
      - completed

jobs:
  # Trabajo independiente inicial
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo validation
        run: echo "Starting validation job - this job has no dependencies."

  # Trabajo principal: Build
  build:
    runs-on: ubuntu-latest
    needs: [validate] # Ahora depende del trabajo "validate"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
